# Generated by Django 5.2 on 2025-08-17 00:00
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        # Example: Add your previous operations here if needed
        # migrations.AddField(
        #     model_name='customuser',
        #     name='reset_token',
        #     field=models.CharField(max_length=255, null=True, blank=True),
        # ),
    ]
