# Generated by Django 5.2 on 2025-08-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_add_reset_token'),
        ('auth_app', '0002_passwordresetotp'),
    ]

    operations = [
    ]
