# Generated by Django 5.2 on 2025-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_packages_pickup_lat_packages_pickup_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='tour_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='tour_location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
